name: k6 Load Test

on:
  push:

jobs:
  run-test:
    runs-on: macos-latest
    
     steps:
    - uses: actions/checkout@v4
    - name: Setup Grafana k6
      uses: ./
      with:
        k6-version: '0.49.0'
    - run: k6 run ./k6-tests/k6-grafana.js
    
